shop-service:
  properties:


spring:
  application:
    name: item-service
    prefix: ite

server:
  servlet:
    context-path: /item-service
  port: ${SERVER_PORT:8899}
  tomcat:
    threads:
      max: ${TOMCAT_MAX_THREADS:50}
      min-spare: ${TOMCAT_MIN_THREADS:20}
    accept-count: ${TOMCAT_ACCEPT_COUNT:300}
    basedir: /
    accesslog:
      enabled: true
      directory: "/logs/item-service"
      prefix: access_log
      buffered: false
      suffix: .log
      file-date-format: .yyyy-MM-dd
      pattern: "%h %l %u %t %r %s %b %D"

external-service:
  shop-service:
    base-url: http://localhost:8898/shop-service
    find-endpoints: /api/v1/public/endpoint

#security:
#  oauth2:
#    resource:
#      token-info-uri: http://localhost:9191/oauth/check_token
#    client:
#      client-id: mobile
#      client-secret: pin